#!/bin/bash

TWITTER_CONSUMER_KEY=3nVuSoBZnx6U4vzUxf5w
TWITTER_CONSUMER_SECRET=Bcs59EFbbsdF6Sl9Ng71smgStWEGwXXKSjYvPVt7qys
TWITTER_ACCESS_TOKEN=
TWITTER_ACCESS_SECRET=

export TWITTER_CONSUMER_KEY TWITTER_CONSUMER_SECRET
export TWITTER_ACCESS_TOKEN TWITTER_ACCESS_SECRET


bundle exec ruby "$1"
